---
- hosts: home | localhost
  connection: local
  become: yes
  
  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no
      
  roles:
    - start

  tasks:   
    - name: set hostname
      hostname:
        name: Home
        use: debian
    - name: update hosts file
      lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1[[:space:]]+localhost'
        line: '127.0.0.1       Home localhost'

  # roles:
  #   - services
