- hosts: localhost
  connection: local
  become: true
  
  tasks:
  - name: Install e/t
    apt:
      name: 
        pkg:
        - sudo
        - nano
        - net-tools
        - nautilus
        - bat
        - sshfs
        - zip
        - unzip
        - tree
        - git
        - gh
        - fuse3
        - wget


