---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: yes
        autoremove: yes 
        autoclean: yes 
      changed_when: False

  roles:
    - base

- name: Conditional tasks for localhost
  hosts: localhost
  connection: local 
  become: yes
  gather_facts: true

  - name: Check if 'ubuntu' user exists
    command: id ubuntu
    ignore_errors: true
    register: ubuntu_user_check

  roles:
    - role: rm_ubuntu
      when: ubuntu_user_check.rc == 0

