---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: yes
        autoremove: yes 
        autoclean: yes 
      changed_when: False
      ignore_errors: yes
      args:
        warn: false

  roles:
    - base
