---
- hosts: set_up
  become: yes

  pre_tasks:
    - name: Check if gathering facts fails
      # meta: end_play
      command: /bin/true
      when: ansible_play_hosts | length != groups['set_up'] | length
      # failed_when: no

    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no
      register: update_result

  roles:
    - start
