---
- hosts: set_up
  become: yes

  pre_tasks:
    - name: Check if it gets locked out
      meta: end_play
      when: ansible_play_hosts | length != groups['set_up'] | length

    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no
      register: update_result

  roles:
    - start
