---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no

  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - base
        - ansible_user
        - sean_user
        
    - name: Check if 'ubuntu' user exists and is unlocked
      command: "id -u ubuntu && passwd -S ubuntu | awk '{print $2}'"
      register: ubuntu_user_check
      ignore_errors: true

    - name: Include the role based on the condition
      include_role:
        name: rm_ubuntu
      when: ubuntu_user_check.rc == 0 and ubuntu_user_check.stdout_lines[1] == "PS"
