---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: yes
        autoremove: yes 
        autoclean: yes 
      changed_when: False

  roles:
    - base

- name: Conditional tasks for localhost
  hosts: localhost
  connection: local 
  become: yes
  gather_facts: true

  tasks:
    - name: Check if 'ubuntu' user exists
      command: id ubuntu
      ignore_errors: true
      register: ubuntu_user_check

    - name: Include the role based on the condition
      include_role:
        name: rm_ubuntu
      when: ubuntu_user_check.rc == 0
