---
- hosts: set_up
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no

  roles:
    - start
