---
- hosts: set_up | localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Debug - Print global variables
      debug:
        var: user
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no

  roles:
    - start
