---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: yes
        autoremove: yes 
        autoclean: yes 
      changed_when: False

  roles:
    - base
    # - ansible_user
    - ssh

- name: Conditional tasks for localhost
  hosts: localhost
  connection: local 
  become: yes
  gather_facts: true

  tasks:
    - name: Check if 'ubuntu' user exists and is unlocked
      command: "id -u ubuntu && passwd -S ubuntu | awk '{print $2}'"
      register: ubuntu_user_check
      ignore_errors: true

    - name: Include the role based on the condition
      include_role:
        name: rm_ubuntu
      when: ubuntu_user_check.rc == 0 and ubuntu_user_check.stdout_lines[1] == "PS"
