---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: yes
        autoremove: yes 
        autoclean: yes 
      changed_when: False

  roles:
    - base
    - { role: rm_ubuntu, when: "'ubuntu' in lookup('command', 'id ubuntu')" }



