---
- hosts: localhost
  connection: local 
  become: yes

  pre_tasks:
    - name: Update Repo's
      apt:
        update_cache: True
        upgrade: yes
        autoremove: True
        autoclean: True
      changed_when: False

  roles:
    - base
