---
- hosts: set_up
  become: yes

  pre_tasks:
    - name: Display the number of hosts
      debug:
        var: ansible_play_hosts | length
    - name: Check if gathering facts fails
      fail:
        msg: "Gathering facts failed. Stopping the playbook."
      when: "'UNREACHABLE' in ansible_facts and ansible_facts['UNREACHABLE']"
      failed_when: no

    - name: Update Repo's
      apt:
        update_cache: yes 
        upgrade: full
        autoremove: yes 
        autoclean: yes 
      changed_when: no
      register: update_result

  roles:
    - start
