- name: Install e/t
  apt:
    name: 
      - sudo
      - nano
      - net-tools
      - nautilus
      - bat
      - sshfs
      - zip
      - unzip
      - tree
      - git
      - gh
      - fuse3
      - wget


