- name: Create ansible user
  user:
    name: ansible
    shell: /bin/bash
    system: yes

- name: copy sudoers_ansible 
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: create vault file 
  template:
    src: vault.j2
    dest: /home/ansible/.vault-pass.txt
    owner: ansible
    group: ansible

- name: Make sure /etc/ansible exists
  file:
    path: /etc/ansible
    state: directory

- name: Create ansible.cfg 
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg

- name: Install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/thegreatestgiant/ansible.git > /dev/null"

