- name: generate ssh template
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

- name: Make sure .ssh directory exists
  file:
    path: "{{ user.home }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy private key
  template:
    src: templates/id_ed25519.j2
    dest: "{{ user.home }}/.ssh/id_ed25519"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy public key
  template:
    src: templates/public_key.j2
    dest: "{{ user.home }}/.ssh/id_ed25519.pub"
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy Authorized Keys
  template:
    src: templates/public_key.j2
    dest: "{{ user.home }}/.ssh/authorized_keys"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy config file
  template:
    src: templates/config.j2
    dest: "{{ user.home }}/.ssh/config"
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"


