- name: Create/Ensure my user
  user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512') }}"
    groups: sudo, docker
    shell: /bin/bash
    append: yes

- name: Set-up ssh for my user
  include_role:
    name: ssh

- name: copy sudoers_ansible
  copy:
    src: sudoers_sean
    dest: /etc/sudoers.d/sean
    owner: root
    group: root
    mode: 0440

- name: Install NvChad For My User
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/NvChad/starter'
    dest: "{{ user.home }}/.config/nvim"
    depth: 1

- name: Install My Config For My User
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/thegreatestgiant/NvChad-Config'
    dest: "{{ user.home }}/.config/nvim/lua/custom"
    depth: 1
