- name: Create/Ensure my user
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    groups: sudo, docker
    shell: /bin/bash
    append: yes

- name: Set-up ssh for my user
  include_role:
    name: ssh


