- name: Create/Ensure my user
  user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512') }}"
    create_home: yes
    groups: sudo, docker
    shell: /bin/bash
    append: yes

- name: Set-up ssh for my user
  include_role:
    name: ssh

- name: copy sudoers_ansible
  copy:
    src: sudoers_sean
    dest: /etc/sudoers.d/sean
    owner: root
    group: root
    mode: 0440
