- name: Check if Docker is installed
  command: "docker --version"
  register: docker_check
  ignore_errors: true
  changed_when: False

- name: Install Docker
  shell: bash -c "$(curl -fsSL https://get.docker.com)"
  when: docker_check.rc != 0

- name: Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker 
    append: yes
