- include_tasks: "{{ item }}"
  with_items:
    - pkgs.yml
    - alias.yml
    - docker.yml

- name: Set TZ
  command: timedatectl set-timezone America/New_York

- name: Install NvChad
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: 'https://github.com/NvChad/starter'
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1

- name: Install My Config
  become_user: "{{ ansible_env.USER }}"
  git:
    repo: 'https://github.com/thegreatestgiant/NvChad-Config'
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/custom"
    depth: 1
