- include_tasks: "{{ item }}"
  with_items:
    - pkgs.yml
    - alias.yml
    - docker.yml

- name: Set TZ
  command: timedatectl set-timezone America/New_York

- name: Move existing Nvim config
  command: mv -f "{{ ansible_env.HOME }}/.config/nvim" "{{ ansible_env.HOME }}/.config/nvim_backup_{{ ansible_date_time.date }}"
  ignore_errors: yes

- name: Install NvChad
  git:
    repo: 'https://github.com/NvChad/starter'
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1

- name: Remove .git from NvChad
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/.git"
    state: "absent"

- name: Install My Config
  git:
    repo: 'https://github.com/thegreatestgiant/NvChad-Config'
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/custom"
    depth: 1
