- include_tasks: "{{ item }}"
  with_items:
    - pkgs.yml
    - alias.yml
    - docker.yml

- name: Set TZ
  command: timedatectl set-timezone America/New_York

- name: Move existing Nvim config
  command: mv -f "{{ ansible_env.HOME }}/.config/nvim" "{{ ansible_env.HOME }}/.config/nvim_backup_{{ ansible_date_time.date }}"
  ignore_errors: yes

- name: Install LazyVim
  git:
    repo: "https://github.com/thegreatestgiant/LazyVim.git"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1
