- include_tasks: tasks/gh_stuff.yml
- include_tasks: tasks/pkgs.yml
- include_tasks: tasks/alias.yml
- include_tasks: tasks/docker.yml
- include_tasks: tasks/nvim.yml

- name: Set TZ
  timezone:
    name: "America/New_York"

