- name: Install NeoVim
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /usr/bin/nvim
    mode: '0755'
    group: root

- name: Make NeoVim work on Ubuntu (>= 22.04)
  shell: add-apt-repository universe -y && apt install libfuse2 -y
  changed_when: False
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | float >= 22.04
