- name: Install All Packages
  apt:
    name: 
      - sudo
      - nano
      - net-tools
      - nautilus
      - bat
      - sshfs
      - zip
      - unzip
      - tree
      - git
      - gnupg
      - fuse3
      - libfuse2
      - wget
      - cron
      - python3-passlib
      - ripgrep
      - python3-pip
    state: present
  changed_when: False

- name: Install NeoVim
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /usr/bin/nvim
    mode: '0755'
    group: root

- name: Install Gh
  include_tasks: gh_stuff.yml
