- name: Install All Packages
  apt:
    name: 
      - sudo
      - nano
      - net-tools
      - nautilus
      - bat
      - sshfs
      - zip
      - unzip
      - tree
      - git
      - gnupg
      - fuse3
      - wget
    state: present
  changed_when: False

- name: Install Gh
  task: gh_stuff.yml
