- name: Download Go
  get_url:
    url: "https://go.dev/dl/go{{ go.version }}.linux-{{ lookup('pipe', 'dpkg --print-architecture') }}.tar.gz"
    dest: /tmp/go.tar
    checksum: "{{ checksum_result }}"
  loop:
    - "{{ go.checksum.1 }}"
    - "{{ go.checksum.2 }}"
  loop_control:
    loop_var: checksum_result

- name: Extract Go
  unarchive:
    src: /tmp/go.tar
    dest: /usr/local/
  # when: checksum_result is succeeded

- name: Add Go to PATH
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:/usr/local/go/bin"
    
