- name: Download Go
  get_url:
    url: "https://go.dev/dl/go{{ go.version }}.linux-{{ lookup('pipe', 'dpkg --print-architecture') }}.tar.gz"
    dest: /tmp/go.tar
    # url: "https://go.dev/dl/go1.21.5.linux-arm64.tar.gz"
    checksum: "sha256:841cced7ecda9b2014f139f5bab5ae31785f35399f236b8b3e75dff2a2978d96"
    # checksum: "{{ item }}"
  # loop:
  #   - "{{ go.checksum.1 }}"
  #   - "{{ go.checksum.2 }}"
  # loop_control:
  #   loop_var: checksum_result

- name: Extract Go
  unarchive:
    src: /tmp/go.tar
    dest: /usr/local/
  # when: checksum_result is succeeded

- name: Add Go to PATH
  lineinfile:
    path: /etc/bash.bashrc
    line: "export PATH=$PATH:/usr/local/go/bin"
    
