---
- name: Install NVM
  script: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
    source {{ user.home }}/.nvm/nvm.sh
  args:
    creates: "{{ user.home }}/.nvm/nvm.sh"

- name: Install Node.js
  shell: "nvm install {{ node_version }}"
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ user.home }}/.nvm"

# - name: Set default Node.js version
#   shell: "nvm alias default {{ node_version }}"
#   args:
#     executable: /bin/bash
#   environment:
#     NVM_DIR: "{{ user.home }}/.nvm"
#
