- name: Check if rclone is installed
  command: command -v rclone
  register: rclone_installed
  ignore_errors: yes

- name: Download rclone
  get_url:
    url: "https://downloads.rclone.org/rclone-current-linux-{{ lookup('pipe', 'dpkg --print-architecture') }}.zip"
    dest: /tmp/rc.zip
  register: rclone_download
  when: rclone_installed.rc != 0

- name: Extract rclone
  unarchive:
    src: /tmp/rc.zip
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
    match:
      - '*/rclone'
    creates: /usr/bin/rclone
  when: rclone_download|success && rclone_installed.rc != 0

- name: Extract rclone man page
  unarchive:
    src: /tmp/rc.zip
    dest: /usr/local/share/man/man1/
    remote_src: yes
    match:
      - '*/rclone.1'
  when: rclone_download|success && rclone_installed.rc != 0

- name: Create Kavita directory
  file:
    path: "{{ user.home }}/Kavita"
    state: directory
    mode: 0755

- name: configure rclone
  copy:
    content: |
      [Kavita-gd]
      type = drive
      scope = drive
      token = {"access_token":"ya29.a0AfB_byA_63uVbAV-knDlW4pbhTEeu07J-X_4XDDJ7MSQIj_ORfDgskgV-OooYqQ-LTac1Ubeq_y_jPgSXAYa-N4VTbePLQG7wHHaEXcYKehKc-D4ITBlWve-oPVaNPkmJGvdtVMqdjsujZvj1a2suk2eYSZ101exxG_66zEaCgYKAWMSARISFQGOcNnChstS8Rhy_GcApg1YoI8vdQ0174","token_type":"Bearer","refresh_token":"1//01p-StAfIcKFNCgYIARAAGAESNwF-L9IrNj0Qwy49SSx6-kzKfsfS8QBQQGcSdj8bGuCGHWX8dH34os19eiXG2MWc7gUL2VUvYI0","expiry":"2023-09-22T18:48:05.198731154-04:00"}
      team_drive = 
    dest: "{{ user.home }}/.config/rclone/rclone.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600

- name: Configure rclone service
  copy:
    content: |
      [Unit]
      Description=rclone

      [Service]
      user={{ user.name }}
      ExecStart=/usr/bin/rclone mount Kavita-gd: {{ user.home }}/Kavita --allow-other --allow-non-empty --vfs-cache-mode full
      Restart=on-abort

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/rclone.service
    group: root
    owner: root
    mode: 0644

- name: Enable and start the service
  systemd:
    name: rclone.service
    enabled: yes
    state: started


